### ISSUE TITLE
library not available: custdev-sapui5

### ISSUE THREAD

**Issue by BardoBravo** [pedroendruweit/AQ-RollSimulator#2]
Hello,
Aparently some SAPUI5 components are not found during NPM install process:

*npm ERR! 404 Not Found: custdev-sapui5-infra-util@**

Regards,
Cláudio Ramos

**Comment by pedroendruweit** [comment]
I have changed this dependency from _custdev-sapui5-infra-util_ to _live-server_.

**Comment by BardoBravo** [comment]
Hello,
It seems that the dependency still persists.
[]s

**Comment by pedroendruweit** [comment]
You can try again. The GruntFile was still pointing to it. I've removed now.
Regards

**Comment by BardoBravo** [comment]
Working now! GREAT!
